const studentsData = [
    {
      id: "id1",
      name: "Shaik Afrid",
      attended: false,
      mobileNumber: 9390558027,
      class: "10th Class",
      section: "A Sec",
      classTeacher: "Shaik Afrid",
    },
    {
      id: "id2",
      name: "John Doe",
      attended: true,
      mobileNumber: 9876543210,
      class: "10th Class",
      section: "B Sec",
      classTeacher: "Jane Doe",
    },
    {
      id: "id3",
      name: "Alice Smith",
      attended: true,
      mobileNumber: 9345678901,
      class: "10th Class",
      section: "A Sec",
      classTeacher: "Shaik Afrid",
    },
    {
      id: "id4",
      name: "Bob Johnson",
      attended: false,
      mobileNumber: 9123456789,
      class: "9th Class",
      section: "C Sec",
      classTeacher: "Shaik Afrid",
    },
    {
      id: "id5",
      name: "Charlie Brown",
      attended: true,
      mobileNumber: 9456781234,
      class: "10th Class",
      section: "A Sec",
      classTeacher: "Shaik Afrid",
    },
    {
      id: "id6",
      name: "David Lee",
      attended: false,
      mobileNumber: 9765432109,
      class: "10th Class",
      section: "B Sec",
      classTeacher: "Jane Doe",
    },
    {
      id: "id7",
      name: "Eve White",
      attended: true,
      mobileNumber: 9871234560,
      class: "10th Class",
      section: "A Sec",
      classTeacher: "Shaik Afrid",
    },
    {
      id: "id8",
      name: "Frank Green",
      attended: false,
      mobileNumber: 9123451234,
      class: "9th Class",
      section: "C Sec",
      classTeacher: "Shaik Afrid",
    },
    {
      id: "id9",
      name: "Grace Black",
      attended: true,
      mobileNumber: 9198765432,
      class: "10th Class",
      section: "A Sec",
      classTeacher: "Shaik Afrid",
    },
    {
      id: "id10",
      name: "Henry Lewis",
      attended: false,
      mobileNumber: 9345673210,
      class: "9th Class",
      section: "B Sec",
      classTeacher: "Jane Doe",
    },
    {
      id: "id11",
      name: "Ivy Hall",
      attended: true,
      mobileNumber: 9876541098,
      class: "10th Class",
      section: "A Sec",
      classTeacher: "Shaik Afrid",
    },
    {
      id: "id12",
      name: "Jack Wilson",
      attended: false,
      mobileNumber: 9456123456,
      class: "10th Class",
      section: "B Sec",
      classTeacher: "Jane Doe",
    },
    {
      id: "id13",
      name: "Kelly Miller",
      attended: true,
      mobileNumber: 9345678932,
      class: "10th Class",
      section: "A Sec",
      classTeacher: "Shaik Afrid",
    },
    {
      id: "id14",
      name: "Liam Martinez",
      attended: false,
      mobileNumber: 9123456783,
      class: "9th Class",
      section: "C Sec",
      classTeacher: "Shaik Afrid",
    },
    {
      id: "id15",
      name: "Mona Taylor",
      attended: true,
      mobileNumber: 9198765436,
      class: "10th Class",
      section: "B Sec",
      classTeacher: "Jane Doe",
    },
    {
      id: "id16",
      name: "Nathan Perez",
      attended: false,
      mobileNumber: 9765431234,
      class: "9th Class",
      section: "A Sec",
      classTeacher: "Shaik Afrid",
    },
    {
      id: "id17",
      name: "Olivia Clark",
      attended: true,
      mobileNumber: 9345676543,
      class: "10th Class",
      section: "A Sec",
      classTeacher: "Shaik Afrid",
    },
    {
      id: "id18",
      name: "Paul Walker",
      attended: false,
      mobileNumber: 9456129876,
      class: "10th Class",
      section: "B Sec",
      classTeacher: "Jane Doe",
    },
    {
      id: "id19",
      name: "Quinn Young",
      attended: true,
      mobileNumber: 9198761234,
      class: "10th Class",
      section: "A Sec",
      classTeacher: "Shaik Afrid",
    },
    {
      id: "id20",
      name: "Rachel Scott",
      attended: false,
      mobileNumber: 9345674321,
      class: "10th Class",
      section: "B Sec",
      classTeacher: "Jane Doe",
    },
  ];

  export default studentsData
  